name: health_360_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  easy_localization: ^3.0.3
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.1
  hooks_riverpod: ^2.4.10

  shared_preferences: ^2.2.2
  solar_icons: ^0.0.5
  flutter_hooks: ^0.20.0
  uuid: ^4.3.3
  build_runner: ^2.4.8
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/translations/
